const searchall = [
    'https://mcstories.com/Titles/A.html',
    'https://mcstories.com/Titles/B.html',
    'https://mcstories.com/Titles/C.html',
    'https://mcstories.com/Titles/D.html',
    'https://mcstories.com/Titles/E.html',
    'https://mcstories.com/Titles/F.html',
    'https://mcstories.com/Titles/G.html',
    'https://mcstories.com/Titles/H.html',
    'https://mcstories.com/Titles/I.html',
    'https://mcstories.com/Titles/J.html',
    'https://mcstories.com/Titles/K.html',
    'https://mcstories.com/Titles/L.html',
    'https://mcstories.com/Titles/M.html',
    'https://mcstories.com/Titles/N.html',
    'https://mcstories.com/Titles/O.html',
    'https://mcstories.com/Titles/P.html',
    'https://mcstories.com/Titles/Q.html',
    'https://mcstories.com/Titles/R.html',
    'https://mcstories.com/Titles/S.html',
    'https://mcstories.com/Titles/T.html',
    'https://mcstories.com/Titles/U.html',
    'https://mcstories.com/Titles/V.html',
    'https://mcstories.com/Titles/W.html',
    'https://mcstories.com/Titles/X.html',
    'https://mcstories.com/Titles/Y.html',
    'https://mcstories.com/Titles/Z.html'
];

const tags = {
    bd: 'https://mcstories.com/Tags/bd.html',
    be: 'https://mcstories.com/Tags/be.html',
    ca: 'https://mcstories.com/Tags/ca.html',
    cb: 'https://mcstories.com/Tags/cb.html',
    ds: 'https://mcstories.com/Tags/ds.html',
    ex: 'https://mcstories.com/Tags/ex.html',
    fd: 'https://mcstories.com/Tags/fd.html',
    ff: 'https://mcstories.com/Tags/ff.html',
    ft: 'https://mcstories.com/Tags/ft.html',
    fu: 'https://mcstories.com/Tags/fu.html',
    gr: 'https://mcstories.com/Tags/gr.html',
    hm: 'https://mcstories.com/Tags/hm.html',
    hu: 'https://mcstories.com/Tags/hu.html',
    in: 'https://mcstories.com/Tags/in.html',
    la: 'https://mcstories.com/Tags/la.html',
    ma: 'https://mcstories.com/Tags/ma.html',
    mc: 'https://mcstories.com/Tags/mc.html',
    md: 'https://mcstories.com/Tags/md.html',
    mf: 'https://mcstories.com/Tags/mf.html',
    mm: 'https://mcstories.com/Tags/mm.html',
    nc: 'https://mcstories.com/Tags/nc.html',
    rb: 'https://mcstories.com/Tags/rb.html',
    sc: 'https://mcstories.com/Tags/sc.html',
    sf: 'https://mcstories.com/Tags/sf.html',
    ts: 'https://mcstories.com/Tags/ts.html',
    ws: 'https://mcstories.com/Tags/ws.html'
};

module.exports = { searchall, tags };
