# wrangler.toml
name = "mcstories-worker-v1"
main = "src/index.js"
compatibility_date = "2024-07-25"
workers_dev = false

# This section correctly enables logs and tracing for your deployed Worker
[observability]
enabled = true

# Binding for your D1 Database
[[d1_databases]]
binding = "STORIES_DB"
database_name = "mcstories-db"
database_id = "b6ac304b-eddc-42ba-acb9-dfb8954d2940"

# Optional section for local development
[dev]
persist_to = ".wrangler/state"