# wrangler.toml
name = "mcstories-worker-v1"
main = "src/index.js"
compatibility_date = "2024-07-25"
compatibility_flags = ["nodejs_compat"]

[[d1_databases]]
binding = "STORIES_DB"
database_name = "mcstories-db"
database_id = "b6ac304b-eddc-42ba-acb9-dfb8954d2940"

# Changed the binding name to match the official documentation
[browser]
binding = "BROWSER"

[triggers]
crons = ["*/5 * * * *"]